### ISSUE TITLE
Missing sample VRED scene file ?

### ISSUE THREAD

**Issue by PixelPartner** [ninjamode/VRED-Leap#1]
Dear Constantin. In your `Collider` class you mentioned to look up its use in the _sample scene_. 
I could not find one. Please either add one or remove the comment referring to it.
Thank you very much for your work and publishing it.

**Comment by ninjamode** [comment]
The demo scene is in the releases section, because it's to big of a binary to put in the repo itself. It's called _VRED_Leap_Motion_Demo.vpb_.

I have included some information on the demo in the main readme.
