### ISSUE TITLE
Please add support for VRED 2021

### ISSUE THREAD

**Issue by inquisitev** [ninjamode/VRED-Leap#2]
Hi, With VRED 2021 the python version has been updated to python 3+. Could you possibly update this repository to support that change? I assume you're familiar with SWIG and I cannot for the life of me figure out how to get that to work.

**Comment by ninjamode** [comment]
I havn't worked with VRED in years and no access to it at the moment, so an update from me is sadly not going to happen. Seeing that Leap Motion is pretty much discontinued and apparently does not officially support Python 3.x, it seems linke quite some work to get this to work again reliably, I'm afraid.
