### ISSUE TITLE
Updated Hands.osb as seen in the GIF

### ISSUE THREAD

**Issue by Janjs** [ninjamode/VRED-Leap#3]
Hi, I´m pretty sure this repository is not being supported anymore but it doesn´t hurt to try.

Any chance to get the updated Hands model as seen in the gif animation?

Thanks!

**Comment by ninjamode** [comment]
Hi!

this repo is indeed unsupported. The hands thing is easy though. It’s not a model, the hand in the gif is programmatically generated. It’s just cylinders between joints and spheres at the joints.

You can find the setup in Leap.py in line 118 https://github.com/ninjamode/VRED-Leap/blob/9f4f24fe022ad10eaf7854eb872f6f53a9a7d569/Leap/Leap.py#L118

The objects (bones and joints) are already in the scene (was simpler at that point), and picked up by name, but could also be created on the fly if needed I guess.


Good luck with your project!

**Comment by Janjs** [comment]
Got it, thank you!!
